name: Echo payload

on:
  pull_request:
    types: [opened, reopened]

jobs:
  echo_payload:
    runs-on: ubuntu-latest
    steps:
      - name: Echo pull request
        run: echo '${{ toJson(github.event.pull_request) }}'
