name: Echo payload

on:
  pull_request:
    types: [review_requested]

jobs:
  echo_payload:
    runs-on: ubuntu-latest
    steps:
      - name: Echo payload
        run: echo '${{ JSON.stringify(github.event) }}'
